[package]
name = "tango"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["sync"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt"] }
hbb_common = { git = "https://github.com/rustdesk/hbb_common.git" }