[package]
name = "my-common"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
tango = { version = "0.1", path = "../tango" }
tokio = { version = "1", features = ["sync"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
