[package]
name = "my-cli"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
my-common = { path = "../my-common" }
tango = { version = "0.1", path = "../tango" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
