[package]
name = "tango-srv"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
tango = { version = "0.1", path = "../tango" }
hbb_common = {path = "../../libs/hbb_common" }